services:
  parks_api:
    build: .
    container_name: parks-api
    command: flask run --host "0.0.0.0" --port 8060 --reload
    ports:
      - 8060:8060
    volumes:
      - .:/app
    networks:
      - day_planner_planner_network

networks:
  day_planner_planner_network:
    external: true